### ISSUE TITLE
Backport of FIX: wrong indentation of  to block in Example yaml into release/1.18.x

### ISSUE THREAD

**Issue by dhiaayachi** [dhiaayachi/consul#636]
## Backport

This PR is auto-generated from #20974 to be assessed for backporting due to the inclusion of the label backport/1.18.

The below text is copied from the body of the original PR.

---

…Ref example yaml file

wrong indentation of
```yaml
to:
      - group: ""
        kind: Service
        name: echo
```
will cause error

```log
ReferenceGrant in version "v1beta1" cannot be handled as a ReferenceGrant: strict decoding error: unknown field "spec.from[0].to"
```

### Description

wrong indentation of 
```yaml
to:
      - group: ""
        kind: Service
        name: echo
```
will cause error

```log
ReferenceGrant in version "v1beta1" cannot be handled as a ReferenceGrant: strict decoding error: unknown field "spec.from[0].to"
```

### PR Checklist

* [ ] updated test coverage
* [✓] external facing docs updated
* [ ] appropriate backport labels added
* [✓ ] not a security concern

---

<details>
<summary> Overview of commits </summary>

  - 3df60ed4aa07f982ec51e139ee0f7049f638d3a7 

</details>
