### ISSUE TITLE
FIX: wrong indentation of  to block in Example yaml

### ISSUE THREAD

**Issue by dhiaayachi** [dhiaayachi/consul#642]
…Ref example yaml file

wrong indentation of
```yaml
to:
      - group: ""
        kind: Service
        name: echo
```
will cause error

```log
ReferenceGrant in version "v1beta1" cannot be handled as a ReferenceGrant: strict decoding error: unknown field "spec.from[0].to"
```

### Description

wrong indentation of 
```yaml
to:
      - group: ""
        kind: Service
        name: echo
```
will cause error

```log
ReferenceGrant in version "v1beta1" cannot be handled as a ReferenceGrant: strict decoding error: unknown field "spec.from[0].to"
```

### PR Checklist

* [ ] updated test coverage
* [✓] external facing docs updated
* [ ] appropriate backport labels added
* [✓ ] not a security concern
