### ISSUE TITLE
Backport of Use correct enterprise meta on wildcard service update into release/1.16.x

### ISSUE THREAD

**Issue by dhiaayachi** [dhiaayachi/consul#888]
## Backport

This PR is auto-generated from #20721 to be assessed for backporting due to the inclusion of the label backport/1.16.

The below text is copied from the body of the original PR.

---

### Description
- When pulling all services in a namespace previously, the query was hardcoded to use the namespace of the gateway service and not the namespace the wildcard actually names

### Testing & Reproduction steps
- This is technically a fix for https://github.com/hashicorp/consul-enterprise, but targeting this repository first.
- To reproduce kubectl apply the following file after helm installing consul-k8s with an image built with this fix

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: '*'
          namespace: 'default'
        - name: '*'
          namespace: 'service1'

---
kind: Namespace
apiVersion: v1
metadata:
  name: service1

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: static-server
  namespace: default
spec:
  protocol: http


---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: static-server
spec:
  destination:
    name: static-server
  sources:
    - name: ingress-gateway
      action: allow

---


apiVersion: v1
kind: Service
metadata:
  name: static-server
spec:
  selector:
    app: static-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      name: static-server
      labels:
        app: static-server
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: static-server
          image: hashicorp/http-echo:latest
          args:
            - -text="hello world"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: static-server

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: static-server
spec:
  protocol: http
---


---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: static-server-3
  namespace: service1
spec:
  destination:
    name: static-server-3
    namespace: service1
  sources:
    - name: ingress-gateway
      action: allow
      namespace: default

---


apiVersion: v1
kind: Service
metadata:
  name: static-server-3
  namespace: service1
spec:
  selector:
    app: static-server-3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server-3
  namespace: service1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server-3
  namespace: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server-3
  template:
    metadata:
      name: static-server-3
      labels:
        app: static-server-3
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: static-server-3
          image: hashicorp/http-echo:latest
          args:
            - -text="hello world from static server 3, namesapce service1"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: static-server-3

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: static-server-3
  namespace: service1
spec:
  protocol: http

```
port forward the ui

```
kubectl port-forward service/consul-server 8501:8501
```

And observe the upstreams on the ingress gateway
https://localhost:8501/ui/~default/dc1/services/ingress-gateway/upstreams

Now kubectl apply the following yaml

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: '*'
          namespace: 'default'
        - name: '*'
          namespace: 'service1'
       - name: '*'
          namespace: 'service2'

---
```

And observe the same link in the UI. If you're running a binary with this fix you will see no change. If running a current version without the fix, all upstreams not in the default namespace will be wiped from the upstreams list.

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

---

<details>
<summary> Overview of commits </summary>

  - 94a0aa2ea76384742fc39b24e0f0c9294673b4ef  - f0e1badd6f9be776f6efe5d5f80e1e52d8a8bf19  - 183dd2fb126b1acf248f497a181db0d8f6d5ff84 

</details>
